x-veld:
  code:

services:
  veld_preprocess_lowercase:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 /veld/code/preprocess_lowercase.py
    environment:
      in_txt_file: null
      out_txt_file: null
      out_data_description: null

