x-veld:
  code:

services:
  veld_preprocess_remove_punctuation:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 -u /veld/code/preprocess_remove_punctuation.py
    environment:
      in_txt_file: null
      out_txt_file: null
      cpu_count: null
      buffer_segments: 10
      out_data_description: null

