x-veld:
  code:

services:
  veld_preprocess_sample:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python3 /veld/code/preprocess_sample.py
    environment:
      in_file: null
      out_file: null
      out_data_description: null
      cpu_count: null
      percentage_sample: null
      sample_random_seed: null
      buffer_segments: 10

