x-veld:
  code:

services:
  veld_preprocess_strip:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: /veld/code/preprocess_strip.sh
    environment:
      in_file: null
      out_file: null
      line_start: null
      line_end: null

